export const COLORS = {
  SPACE_VOID: '#000000',

  RAILWAY_AMBER: '#FF8C00',
  TRANSIT_CYAN: '#00FFFF',

  FLIGHT_COMMERCIAL: '#FFFFFF',
  FLIGHT_MILITARY: '#FF3333',
  ESTIMATED_GHOST: '#444444',

  QUAKE_RED: '#FF0000',
  VOLCANO_ORANGE: '#FF4500',
} as const;

export const OPACITY = {
  WEATHER_RASTER_BASE: 0.6,
  TRANSIT_UNFOCUSED: 0.2,
  RADAR_SWEEP: 0.8,
} as const;
