export type SourceAccess =
  | 'no_key'
  | 'optional_key'
  | 'free_key'
  | 'free_trial'
  | 'paid'
  | 'local_file'
  | 'login_required';

export type SourceRuntimeStatus =
  | 'working'
  | 'working_with_key'
  | 'missing_key'
  | 'failing'
  | 'stale'
  | 'offline'
  | 'not_implemented'
  | 'not_tested';

export type SourceCategory =
  | 'aviation'
  | 'weather'
  | 'maritime'
  | 'space'
  | 'imagery'
  | 'terrain'
  | 'infrastructure'
  | 'hazards'
  | 'events'
  | 'population'
  | 'economy'
  | 'cameras'
  | 'custom';

export type IntelSource = {
  id: string;
  name: string;
  category: SourceCategory;
  dataType: string;
  formats: string[];
  access: SourceAccess;
  apiKeyRequired: boolean;
  envVars?: string[];
  websiteUrl: string;
  docsUrl?: string;
  enabledByDefault: boolean;
  implemented: boolean;
  codePaths?: string[];
  fallbackSources?: string[];
  notes?: string;
};

export const SOURCE_REGISTRY: IntelSource[] = [
  {
    id: 'airplanes_live',
    name: 'Airplanes.live',
    category: 'aviation',
    dataType: 'Live aircraft positions',
    formats: ['aircraft.json.gz', 'JSON'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://airplanes.live/',
    docsUrl: 'https://airplanes.live/api-guide/',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['server/services/fetchers.mjs'],
    fallbackSources: ['custom_expansion_api', 'opensky', 'adsb_lol'],
  },
  {
    id: 'adsb_lol',
    name: 'api.adsb.lol',
    category: 'aviation',
    dataType: 'Aircraft intelligence flags and metadata',
    formats: ['JSON'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://api.adsb.lol/',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['server/services/intelFetcher.mjs'],
    fallbackSources: ['aircraft_local'],
  },
  {
    id: 'aircraft_local',
    name: 'Local aircraft database',
    category: 'aviation',
    dataType: 'Aircraft identity, registration, model, owner/operator',
    formats: ['gzip CSV', 'semicolon CSV', 'header CSV'],
    access: 'local_file',
    apiKeyRequired: false,
    websiteUrl: 'data_raw/reference/aviation/aircraft.csv.gz',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['backend/src/services/aircraftIndex.mjs'],
  },
  {
    id: 'airports_local',
    name: 'Local airports database / OurAirports',
    category: 'aviation',
    dataType: 'Airport metadata and locations',
    formats: ['CSV'],
    access: 'local_file',
    apiKeyRequired: false,
    websiteUrl: 'https://ourairports.com/data/',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['server/services/airportIndex.mjs', 'server/index.mjs'],
  },
  {
    id: 'openweathermap',
    name: 'OpenWeatherMap Weather Maps',
    category: 'weather',
    dataType: 'Global weather map tiles',
    formats: ['XYZ PNG tiles'],
    access: 'optional_key',
    apiKeyRequired: true,
    envVars: ['VITE_OWM_API_KEY', 'OWM_API_KEY', 'OPENWEATHER_API_KEY'],
    websiteUrl: 'https://openweathermap.org/',
    docsUrl: 'https://openweathermap.org/api/weather-map-2',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['server/services/ClimateEngine.mjs'],
    fallbackSources: ['rainviewer', 'open_meteo'],
  },
  {
    id: 'rainviewer',
    name: 'RainViewer',
    category: 'weather',
    dataType: 'Radar fallback and precipitation tiles',
    formats: ['JSON index', 'PNG tiles'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.rainviewer.com/',
    docsUrl: 'https://www.rainviewer.com/api/weather-maps-api.html',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['server/services/ClimateEngine.mjs', 'src/core/api/weatherApi.ts'],
    fallbackSources: ['open_meteo'],
  },
  {
    id: 'open_meteo',
    name: 'Open-Meteo',
    category: 'weather',
    dataType: 'Point weather, forecast, and air quality',
    formats: ['JSON'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://open-meteo.com/',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['src/core/api/weatherApi.ts', 'src/engine/WeatherInspectorRenderer.ts'],
  },
  {
    id: 'submarine_cable_map',
    name: 'Submarine Cable Map',
    category: 'infrastructure',
    dataType: 'Subsea cable routes',
    formats: ['GeoJSON'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.submarinecablemap.com/',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['server/services/infrastructureFetcher.mjs'],
  },
  {
    id: 'global_fishing_watch',
    name: 'Global Fishing Watch',
    category: 'maritime',
    dataType: 'Maritime vessel presence and trade activity',
    formats: ['JSON REST API'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['GFW_API_KEY', 'GLOBAL_FISHING_WATCH_API_KEY', 'GFW_TOKEN'],
    websiteUrl: 'https://globalfishingwatch.org/',
    docsUrl: 'https://globalfishingwatch.org/our-apis/',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['server/services/gfwService.mjs', 'server/index.mjs'],
    fallbackSources: ['aisstream', 'marinecadastre_ais', 'osm'],
  },
  {
    id: 'aisstream',
    name: 'AISStream',
    category: 'maritime',
    dataType: 'Live AIS ships',
    formats: ['WebSocket JSON'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['AISSTREAM_API_KEY'],
    websiteUrl: 'https://aisstream.io/',
    docsUrl: 'https://aisstream.io/documentation',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['server/services/shipFetcher.mjs'],
    fallbackSources: ['global_fishing_watch', 'marinecadastre_ais'],
  },
  {
    id: 'spacetrack',
    name: 'Space-Track',
    category: 'space',
    dataType: 'Satellite GP/TLE catalog',
    formats: ['JSON GP records', 'TLE'],
    access: 'login_required',
    apiKeyRequired: true,
    envVars: ['SPACETRACK_EMAIL', 'SPACETRACK_USERNAME', 'SPACETRACK_PASSWORD'],
    websiteUrl: 'https://www.space-track.org/',
    docsUrl: 'https://www.space-track.org/documentation',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['server/services/satelliteFetcher.mjs'],
  },
  {
    id: 'opensky',
    name: 'OpenSky',
    category: 'aviation',
    dataType: 'Aircraft routes and traces',
    formats: ['JSON REST API'],
    access: 'optional_key',
    apiKeyRequired: false,
    envVars: ['OPENSKY_CLIENT_ID', 'OPENSKY_CLIENT_SECRET'],
    websiteUrl: 'https://opensky-network.org/',
    docsUrl: 'https://openskynetwork.github.io/opensky-api/rest.html',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['server/services/opensky.mjs', 'server/flights-proxy.mjs'],
    fallbackSources: ['airports_local'],
  },
  {
    id: 'cesium_ion',
    name: 'Cesium ion',
    category: 'terrain',
    dataType: 'Terrain, 3D Tiles, ion imagery',
    formats: ['terrain', 'imagery', '3D Tiles'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['VITE_CESIUM_ION_TOKEN', 'CESIUM_ION_TOKEN'],
    websiteUrl: 'https://cesium.com/ion/',
    docsUrl: 'https://cesium.com/learn/ion/cesium-ion-access-tokens/',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['src/earth/viewer/viewerConfig.ts', 'src/engine/ViewerRuntime.ts'],
    fallbackSources: ['arcgis', 'osm'],
  },
  {
    id: 'arcgis',
    name: 'ArcGIS basemaps',
    category: 'imagery',
    dataType: 'Public basemap imagery',
    formats: ['raster tiles', 'service JSON'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.arcgis.com/',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['src/earth/viewer/imageryOptions.ts'],
  },
  {
    id: 'osm',
    name: 'OpenStreetMap',
    category: 'infrastructure',
    dataType: 'Base map and infrastructure data',
    formats: ['raster tiles', 'OSM PBF', 'OSM XML'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.openstreetmap.org/',
    enabledByDefault: true,
    implemented: true,
    codePaths: ['src/earth/viewer/imageryOptions.ts'],
    fallbackSources: ['geofabrik'],
  },
  {
    id: 'stadia',
    name: 'Stadia Maps',
    category: 'imagery',
    dataType: 'Basemap tiles',
    formats: ['raster tiles', 'vector tiles'],
    access: 'optional_key',
    apiKeyRequired: true,
    envVars: ['STADIA_MAPS_API_KEY'],
    websiteUrl: 'https://stadiamaps.com/',
    docsUrl: 'https://docs.stadiamaps.com/authentication/',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['src/earth/viewer/imageryOptions.ts'],
  },
  {
    id: 'maptiler',
    name: 'MapTiler',
    category: 'imagery',
    dataType: 'Satellite and tactical transit tiles',
    formats: ['TileJSON', 'XYZ tiles', 'WMTS'],
    access: 'optional_key',
    apiKeyRequired: true,
    envVars: ['VITE_MAPTILER_API_KEY', 'MAPTILER_API_KEY'],
    websiteUrl: 'https://www.maptiler.com/',
    docsUrl: 'https://docs.maptiler.com/cloud/api/tiles/',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['src/earth/viewer/imageryOptions.ts', 'src/engine/TransitRenderer.ts'],
  },
  {
    id: 'custom_expansion_api',
    name: 'Custom expansion API',
    category: 'custom',
    dataType: 'User-defined aircraft/intelligence feed',
    formats: ['JSON'],
    access: 'optional_key',
    apiKeyRequired: false,
    envVars: ['CUSTOM_API_URL', 'CUSTOM_API_KEY', 'GODS_EXPANSION_API_KEY'],
    websiteUrl: 'custom',
    enabledByDefault: false,
    implemented: true,
    codePaths: ['server/services/fetchers.mjs'],
  },
  {
    id: 'usgs_earthquakes',
    name: 'USGS Earthquake API',
    category: 'hazards',
    dataType: 'Earthquake events',
    formats: ['GeoJSON', 'CSV', 'QuakeML'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://earthquake.usgs.gov/',
    docsUrl: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'nasa_firms',
    name: 'NASA FIRMS',
    category: 'hazards',
    dataType: 'Active fires',
    formats: ['CSV', 'KML', 'map services'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['NASA_FIRMS_MAP_KEY'],
    websiteUrl: 'https://firms.modaps.eosdis.nasa.gov/',
    docsUrl: 'https://firms.modaps.eosdis.nasa.gov/api/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'nasa_gibs',
    name: 'NASA GIBS',
    category: 'imagery',
    dataType: 'Earth observation imagery',
    formats: ['WMTS', 'WMS', 'TWMS', 'TMS'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.earthdata.nasa.gov/',
    docsUrl: 'https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'gdelt',
    name: 'GDELT',
    category: 'events',
    dataType: 'News and event signals',
    formats: ['JSON', 'CSV', 'BigQuery'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.gdeltproject.org/',
    docsUrl: 'https://www.gdeltproject.org/data.html',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'natural_earth',
    name: 'Natural Earth',
    category: 'infrastructure',
    dataType: 'Boundaries, coastlines, populated places',
    formats: ['Shapefile', 'GeoPackage', 'SQLite', 'raster'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.naturalearthdata.com/',
    docsUrl: 'https://www.naturalearthdata.com/downloads/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'geofabrik',
    name: 'Geofabrik OSM Extracts',
    category: 'infrastructure',
    dataType: 'Regional OSM extracts',
    formats: ['OSM PBF', 'shapefile'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://download.geofabrik.de/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'worldpop',
    name: 'WorldPop',
    category: 'population',
    dataType: 'Population grids',
    formats: ['GeoTIFF', 'CSV', 'metadata API'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.worldpop.org/',
    docsUrl: 'https://www.worldpop.org/sdi/introapi/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'hdx',
    name: 'HDX',
    category: 'events',
    dataType: 'Humanitarian datasets',
    formats: ['CSV', 'GeoJSON', 'XLSX', 'Shapefile', 'CKAN API'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://data.humdata.org/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'reliefweb',
    name: 'ReliefWeb',
    category: 'events',
    dataType: 'Humanitarian reports',
    formats: ['JSON API'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://reliefweb.int/',
    docsUrl: 'https://apidoc.reliefweb.int/v0/index.html',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'gdacs',
    name: 'GDACS',
    category: 'hazards',
    dataType: 'Global disaster alerts',
    formats: ['RSS', 'XML', 'JSON'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.gdacs.org/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'acled',
    name: 'ACLED',
    category: 'events',
    dataType: 'Conflict and protest events',
    formats: ['API', 'CSV'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['ACLED_API_KEY'],
    websiteUrl: 'https://acleddata.com/',
    docsUrl: 'https://acleddata.com/acled-api-documentation',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'mobility_database',
    name: 'Mobility Database',
    category: 'infrastructure',
    dataType: 'Transit feed catalog',
    formats: ['catalog API', 'GTFS ZIP', 'GTFS-RT protobuf', 'GBFS JSON'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://mobilitydatabase.org/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'gtfs',
    name: 'GTFS',
    category: 'infrastructure',
    dataType: 'Transit schedules',
    formats: ['ZIP of CSV files'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://gtfs.org/schedule/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'gtfs_realtime',
    name: 'GTFS Realtime',
    category: 'infrastructure',
    dataType: 'Transit vehicle positions and alerts',
    formats: ['Protocol Buffers'],
    access: 'optional_key',
    apiKeyRequired: false,
    websiteUrl: 'https://gtfs.org/realtime/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'openrailwaymap',
    name: 'OpenRailwayMap / OSM rail',
    category: 'infrastructure',
    dataType: 'Rail infrastructure',
    formats: ['OSM PBF', 'GeoJSON', 'map tiles'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.openrailwaymap.org/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'marinecadastre_ais',
    name: 'MarineCadastre AIS',
    category: 'maritime',
    dataType: 'U.S. AIS history',
    formats: ['File geodatabase', 'GIS downloads'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://marinecadastre.gov/accessais/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'worldbank',
    name: 'World Bank Indicators API',
    category: 'economy',
    dataType: 'Country indicators',
    formats: ['JSON', 'XML', 'CSV'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://data.worldbank.org/',
    docsUrl: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'imf',
    name: 'IMF Data API',
    category: 'economy',
    dataType: 'Macroeconomic indicators',
    formats: ['SDMX API'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://data.imf.org/',
    docsUrl: 'https://data.imf.org/en/Resource-Pages/IMF-API',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'un_comtrade',
    name: 'UN Comtrade',
    category: 'economy',
    dataType: 'Trade/import/export data',
    formats: ['JSON', 'CSV'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['UN_COMTRADE_API_KEY'],
    websiteUrl: 'https://comtradedeveloper.un.org/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'eia',
    name: 'EIA Open Data',
    category: 'economy',
    dataType: 'Energy, electricity, petroleum, gas, prices',
    formats: ['JSON API', 'bulk downloads'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['EIA_API_KEY'],
    websiteUrl: 'https://www.eia.gov/opendata/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'openinframap',
    name: 'OpenInfraMap / OSM infrastructure',
    category: 'infrastructure',
    dataType: 'Power lines, substations, pipelines, telecoms',
    formats: ['OSM-derived data'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://openinframap.org/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'open_charge_map',
    name: 'Open Charge Map',
    category: 'infrastructure',
    dataType: 'EV charging stations',
    formats: ['JSON API', 'KML'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['OPENCHARGEMAP_API_KEY'],
    websiteUrl: 'https://openchargemap.org/site/develop/api',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'copernicus_land',
    name: 'Copernicus Land Monitoring Service',
    category: 'infrastructure',
    dataType: 'Land cover, vegetation, water, ground motion',
    formats: ['GeoTIFF', 'NetCDF'],
    access: 'free_key',
    apiKeyRequired: false,
    websiteUrl: 'https://land.copernicus.eu/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'usgs_landsat',
    name: 'USGS Landsat',
    category: 'imagery',
    dataType: 'Satellite imagery and land change',
    formats: ['GeoTIFF', 'COG'],
    access: 'free_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.usgs.gov/landsat-missions',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'noaa_gfs',
    name: 'NOAA GFS',
    category: 'weather',
    dataType: 'Global forecast model',
    formats: ['GRIB2'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.ncei.noaa.gov/products/weather-climate-models/global-forecast',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'dwd_icon',
    name: 'DWD ICON',
    category: 'weather',
    dataType: 'Weather forecast model',
    formats: ['GRIB2'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.dwd.de/EN/ourservices/nwp_forecast_data/nwp_forecast_data.html',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'ecmwf_open_data',
    name: 'ECMWF Open Data',
    category: 'weather',
    dataType: 'Forecast model data',
    formats: ['GRIB2', 'BUFR'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://www.ecmwf.int/en/forecasts/datasets/open-data',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'noaa_nexrad',
    name: 'NOAA NEXRAD',
    category: 'weather',
    dataType: 'U.S. weather radar',
    formats: ['Level II', 'Level III radar files'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://registry.opendata.aws/noaa-nexrad/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'noaa_mrms',
    name: 'NOAA MRMS / NOAA Open Data',
    category: 'weather',
    dataType: 'Multi-radar precipitation/severe products',
    formats: ['GRIB2'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://registry.opendata.aws/collab/noaa/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'noaa_goes',
    name: 'NOAA GOES',
    category: 'imagery',
    dataType: 'Geostationary satellite imagery',
    formats: ['NetCDF'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://registry.opendata.aws/noaa-goes/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'himawari',
    name: 'Himawari',
    category: 'imagery',
    dataType: 'Asia-Pacific satellite imagery',
    formats: ['NetCDF', 'HSD'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://registry.opendata.aws/noaa-himawari/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'eumetsat_meteosat',
    name: 'EUMETSAT / Meteosat',
    category: 'imagery',
    dataType: 'Europe/Africa/Indian Ocean satellite imagery',
    formats: ['product-dependent'],
    access: 'free_key',
    apiKeyRequired: false,
    websiteUrl: 'https://data.eumetsat.int/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'windy_webcams',
    name: 'Windy Webcams',
    category: 'cameras',
    dataType: 'Public webcams, previews, timelapses',
    formats: ['JSON API', 'image URLs', 'embeds'],
    access: 'free_key',
    apiKeyRequired: true,
    envVars: ['WINDY_WEBCAMS_API_KEY'],
    websiteUrl: 'https://api.windy.com/webcams/docs',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'earthcam',
    name: 'EarthCam',
    category: 'cameras',
    dataType: 'Public scenic webcams',
    formats: ['embed', 'player', 'partner API'],
    access: 'paid',
    apiKeyRequired: true,
    envVars: ['EARTHCAM_API_KEY'],
    websiteUrl: 'https://www.earthcam.net/api/',
    enabledByDefault: false,
    implemented: false,
  },
  {
    id: 'city_open_data_cameras',
    name: 'City open-data cameras',
    category: 'cameras',
    dataType: 'Official public city camera links',
    formats: ['CSV', 'JSON', 'ArcGIS', 'Socrata'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://opendata.vancouver.ca/explore/dataset/web-cam-url-links/api/',
    enabledByDefault: true,
    implemented: false,
  },
  {
    id: 'opendatacam',
    name: 'OpenDataCam',
    category: 'cameras',
    dataType: 'Self-hosted visual-analysis tool',
    formats: ['local API', 'JSON output'],
    access: 'no_key',
    apiKeyRequired: false,
    websiteUrl: 'https://opendata.cam/',
    enabledByDefault: false,
    implemented: false,
    notes: 'Use only on camera streams where analysis is explicitly allowed.',
  },
];
