INSERT INTO sources (
  source_id,
  source_family,
  display_name,
  global_best_effort,
  priority_current,
  priority_historical,
  docs_url
) VALUES
  ('open_meteo', 'global_weather_api', 'Open-Meteo', true, 10, 40, 'https://open-meteo.com/en/docs'),
  ('noaa_nodd_gfs', 'global_weather_model', 'NOAA GFS / NODD', true, 40, 50, 'https://registry.opendata.aws/noaa-gfs-bdp-pds/'),
  ('climate_air_reference', 'global_climate_reference', 'Climate and air reference catalogs', true, 70, 10, NULL),
  ('nasa_gibs', 'global_satellite_imagery', 'NASA GIBS', true, 60, 60, 'https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api'),
  ('nasa_firms', 'global_active_fire', 'NASA FIRMS', true, 20, 30, 'https://firms.modaps.eosdis.nasa.gov/api/'),
  ('openaq', 'global_air_quality', 'OpenAQ', true, 20, 30, 'https://docs.openaq.org/'),
  ('gdacs', 'global_disaster_alerts', 'GDACS', true, 20, 30, 'https://gdacs.org/feed_reference.aspx'),
  ('usgs_earthquake', 'global_earthquake', 'USGS Earthquake', true, 10, 20, 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php'),
  ('usgs', 'global_earthquake', 'USGS legacy compatibility', true, 10, 20, 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php'),
  ('worldpop', 'global_population', 'WorldPop', true, 80, 40, 'https://www.worldpop.org/sdi/introapi/'),
  ('copernicus_land_clms', 'global_land_surface', 'Copernicus Land Monitoring Service', true, 60, 30, 'https://land.copernicus.eu/'),
  ('nasa_earthdata_modis', 'global_satellite_land', 'NASA Earthdata / MODIS', true, 60, 30, 'https://cmr.earthdata.nasa.gov/search/site/docs/search/api'),
  ('rainviewer', 'global_radar_tiles', 'RainViewer', true, 50, 60, 'https://www.rainviewer.com/api.html'),
  ('reference_context', 'global_reference_context', 'Reference context sources', true, 80, 60, NULL),
  ('noaa_goes', 'satellite_imagery', 'NOAA GOES', false, 50, 60, 'https://registry.opendata.aws/noaa-goes/'),
  ('noaa_cyclone', 'global_cyclone_tracking', 'NOAA Cyclone / NHC / JTWC', true, 25, 40, NULL),
  ('noaa_dart', 'global_ocean_tsunami', 'NOAA DART / NDBC', true, 25, 40, 'https://www.ndbc.noaa.gov/dart/dart.shtml'),
  ('noaa_nwps', 'regional_hydrology_forecast', 'NOAA NWPS', false, 25, 40, 'https://water.noaa.gov/about/api'),
  ('smithsonian_gvp', 'global_volcano_reference', 'Smithsonian GVP', true, 60, 30, 'https://volcano.si.edu/'),
  ('usgs_volcano', 'regional_volcano_alerts', 'USGS Volcano Hazards Program', false, 30, 40, 'https://volcanoes.usgs.gov/vsc/api/'),
  ('noaa_nws', 'regional_weather_alerts', 'NOAA/NWS', false, 15, 40, 'https://www.weather.gov/documentation/services-web-api'),
  ('noaa_marine', 'regional_marine_weather', 'NOAA Marine / NDBC / CO-OPS', false, 20, 40, 'https://www.ndbc.noaa.gov/'),
  ('noaa_spc', 'regional_severe_weather', 'NOAA SPC', false, 20, 40, 'https://www.spc.noaa.gov/products/outlook/'),
  ('noaa_radar', 'regional_radar', 'NOAA Radar', false, 30, 50, NULL),
  ('usgs_water', 'regional_hydrology', 'USGS Water', false, 25, 40, 'https://api.waterdata.usgs.gov/')
ON CONFLICT (source_id) DO UPDATE SET
  source_family = EXCLUDED.source_family,
  display_name = EXCLUDED.display_name,
  global_best_effort = EXCLUDED.global_best_effort,
  priority_current = EXCLUDED.priority_current,
  priority_historical = EXCLUDED.priority_historical,
  docs_url = EXCLUDED.docs_url;
