INSERT INTO parameter_registry (
  parameter_id,
  canonical_name,
  display_name,
  category,
  data_family,
  canonical_unit,
  value_kind,
  geometry_kind,
  storage_target,
  is_direct,
  is_derived,
  is_grid,
  is_event,
  is_alert,
  is_visual,
  primary_sources,
  fallback_sources,
  aggregation_rule,
  retention_rule,
  notes
) VALUES
  ('temperature', 'temperature', 'Temperature', 'weather', 'weather_time_series', 'degC', 'observation_or_forecast', 'point', 'postgres', true, false, false, false, false, false, ARRAY['open_meteo'], ARRAY[]::text[], 'avg/min/max', 'mvp_recent_timescale', 'MVP Open-Meteo temperature.'),
  ('pressure', 'pressure', 'Pressure', 'weather', 'weather_time_series', 'hPa', 'observation_or_forecast', 'point', 'postgres', true, false, false, false, false, false, ARRAY['open_meteo'], ARRAY[]::text[], 'latest/avg', 'mvp_recent_timescale', 'MVP pressure_msl.'),
  ('wind_speed', 'wind_speed', 'Wind Speed', 'weather', 'weather_time_series', 'm/s', 'observation_or_forecast', 'point', 'postgres', true, false, false, false, false, false, ARRAY['open_meteo'], ARRAY[]::text[], 'avg/max', 'mvp_recent_timescale', 'MVP wind speed normalized from km/h when needed.'),
  ('wind_direction', 'wind_direction', 'Wind Direction', 'weather', 'weather_time_series', 'degree', 'observation_or_forecast', 'point', 'postgres', true, false, false, false, false, false, ARRAY['open_meteo'], ARRAY[]::text[], 'latest/vector', 'mvp_recent_timescale', 'MVP wind direction.'),
  ('rainfall', 'rainfall', 'Rainfall', 'weather', 'weather_time_series', 'mm', 'observation_or_forecast', 'point', 'postgres', true, false, false, false, false, false, ARRAY['open_meteo'], ARRAY[]::text[], 'sum', 'mvp_recent_timescale', 'MVP rain/precipitation.'),
  ('humidity', 'humidity', 'Humidity', 'weather', 'weather_time_series', '%', 'observation_or_forecast', 'point', 'postgres', true, false, false, false, false, false, ARRAY['open_meteo'], ARRAY[]::text[], 'avg/max', 'mvp_recent_timescale', 'MVP relative humidity.'),
  ('earthquake_magnitude', 'earthquake_magnitude', 'Earthquake Magnitude', 'hazard', 'hazard_events', null, 'event', 'point', 'postgres', true, false, false, true, false, false, ARRAY['usgs_earthquake'], ARRAY['gdacs'], 'max/latest', 'mvp_later', 'Seeded now; adapter later.'),
  ('active_fire', 'active_fire', 'Active Fire', 'wildfire', 'hazard_events', null, 'event', 'point', 'postgres', true, false, false, true, false, false, ARRAY['nasa_firms'], ARRAY['gdacs'], 'count/latest', 'mvp_later', 'Seeded now; adapter later.')
ON CONFLICT (parameter_id) DO UPDATE SET
  canonical_name = EXCLUDED.canonical_name,
  display_name = EXCLUDED.display_name,
  category = EXCLUDED.category,
  data_family = EXCLUDED.data_family,
  canonical_unit = EXCLUDED.canonical_unit,
  value_kind = EXCLUDED.value_kind,
  geometry_kind = EXCLUDED.geometry_kind,
  storage_target = EXCLUDED.storage_target,
  is_direct = EXCLUDED.is_direct,
  is_derived = EXCLUDED.is_derived,
  is_grid = EXCLUDED.is_grid,
  is_event = EXCLUDED.is_event,
  is_alert = EXCLUDED.is_alert,
  is_visual = EXCLUDED.is_visual,
  primary_sources = EXCLUDED.primary_sources,
  fallback_sources = EXCLUDED.fallback_sources,
  aggregation_rule = EXCLUDED.aggregation_rule,
  retention_rule = EXCLUDED.retention_rule,
  notes = EXCLUDED.notes;

